version: '3'
services:
  jenkins:
        build: .
        container_name: jenkins
        ports:
          - "8080:8080"
        deploy:
            restart_policy:
              condition: on-failure
            resources:
              limits:
                cpus: '0.25'
                memory: 1000M
        tty: true
