version: '3.3'
volumes:
  data:
  wordpress_files:
services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SENHA
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    deploy:
        restart_policy:
          condition: on-failure
    tty: true
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    deploy:
       restart_policy:
         condition: on-failure
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 1880:80
    environment:
      - PMA_ARBITRARY=1
    deploy:
        restart_policy:
          condition: on-failure
    tty: true
