version: '2'
#https://github.com/krull/docker-janus
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  janus-gateway:
    image: mcroth/docker-janus:latest 
    container_name: janus-gateway
    user: root
    volumes:
      - ./janus/etc/janus/:/opt/janus/etc/janus/
      - ./janus/janus.log:/var/log/janus.log
    ports:  
      - 8088:8088
      - 8188:8188
    networks:
      - back-tier
      - front-tier