version: "2.1"
#funciona melhor esse aqui
#https://wiki.processmaker.com/3.1/ProcessMaker_CentOS_RHEL_Installation
services:
   mysql:
     image: mysql:5.6
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: SENHA
     networks:
     - pm-net

   processmaker:
     depends_on:
     - mysql
     image: processmaker/processmaker:latest
     ports:
       - "80:80"
     restart: always
     networks:
      - pm-net

networks:
  pm-net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.150.0/24
