version: '3'
services:
  nodered:
        build: .
        image: centos_nodered:latest
        container_name: lg2
        volumes:
            - /npm_dir:/npm_dir
        ports:
          - "1880:1880"
        deploy:
            restart_policy:
              condition: on-failure
            resources:
              limits:
                cpus: '0.25'
                memory: 1000M
        tty: true
