version: '2'
services:
  mongodb:
    image: mongo:3
    user: root
  mongosetup:
    image: mongo:3.2
    volumes:
      - "/volume_graylog/mongo:/dump"
    entrypoint: ["mongorestore", "-d", "graylog", "/dump"]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    user: root
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "/volume_graylog/elasticsearch:/usr/share/elasticsearch/data"
  graylog:
    image: graylog/graylog:3.1.0-beta.3-1
    user: root
    volumes:
      - "/volume_graylog/plugin:/usr/share/graylog/plugin"
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=somepasswordpepper
      - GRAYLOG_HTTP_EXTERNAL_URI=http://54.39.180.205:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp